#!/bin/sh /etc/rc.common

START=97

start () {
    uci set fastd.mesh_vpn.on_connect='/usr/sbin/ffs-set-segment'
    if [ -d "/proc/$(cat /var/run/fastd.mesh_vpn.pid)" ]; then
        /etc/init.d/fastd restart
    fi

    rm /tmp/.seg.ffs
    /etc/init.d/micrond enable
    /etc/init.d/micrond restart
}

stop() {
    true
}
