#!/bin/sh
ME=$(basename $0)
if [ $(ps | grep -c "$ME") -gt 4 ]; then
  logger -s -t $ME "started twice"
  exit 1
fi

FFS=/tmp/.gw.ffs
if [ "$(uci get gluon-setup-mode.@setup_mode[0].enabled)" = "0" ] &&
   [ "$(uci get system.@system[0].enable_watchdog)" != "0" ] &&
   [ "$(netstat -nt | grep -c ':22')" = "0" ]; then

  if [ -n "$(batctl gwl | grep '=>')" ]; then
    echo 0 >$FFS
    logger -t $ME "node is online"
  else
    if [ -f $FFS ]; then
      OFF=$(cat $FFS)
    else
      OFF=1
    fi
      
    logger -t $ME "offline count: ${OFF}"

    if [ $OFF -gt 10 ]; then
      reboot
    else
      echo $((OFF+1)) >$FFS
    fi
  fi
else
  rm $FFS
  logger -t $ME "disabled"
fi
