#!/bin/sh

# Content based on patches from FFRN
# only do something if less than 40megs of RAM
RAMSIZE=`grep MemTotal /proc/meminfo | awk '{print $2}'`
if [ $RAMSIZE -le 40000 ] ; then

    # start haveged in config mode, else disable and stop it
    MODE=`uci get gluon-setup-mode.@setup_mode[0].enabled`
    if [ $MODE == "1" ] ; then
        /etc/init.d/haveged start
    elif [ -f /etc/rc.d/S13haveged ] ; then
        /etc/init.d/haveged disable
        /etc/init.d/haveged stop
    fi
fi
