#!/bin/sh
if [  $(ps | grep -c "{$(basename $0)}") -gt 4 ]; then
    exit 1
fi

if [  $(ps | grep -c "fastd") -lt 2 ]; then
    exit 0
fi

if [ "$(uci get fastd.mesh_vpn_backbone.auto_segment)" = "0" ]; then
    exit 0
fi 

NODEID=`uci get network.bat0.macaddr`
for i in `seq 1 5`;
do
    NODEID=${NODEID/\:/}
done
NODEID=ffs-$NODEID
SEGMENT=`nslookup $NODEID.segassign.freifunk-stuttgart.de  [::1]:54 |tail -n1 `
if [[ -z "${SEGMENT// }" ]]; then
    exit 1
fi
SEGMENT=${SEGMENT/Address 1: 2001:2:0:711::/}
let PORT=SEGMENT+10040
SEGNUM=$(printf "%02d" $SEGMENT)

CHANGED=0
for i in `seq 1 10`;
do
    GW=$(printf "gw%02d" $i)
    OLDPEER=`uci get fastd.mesh_vpn_backbone_peer_$GW.remote`
    NEWPEER="\"${GW}s$SEGNUM.freifunk-stuttgart.de\" port $PORT"

    if [ "$NEWPEER" != "$OLDPEER" ]; then
        uci set fastd.mesh_vpn_backbone_peer_$GW.remote="$NEWPEER"
        CHANGED=1
    fi
done

if [ "$CHANGED" = "1" ]; then
    /etc/init.d/fastd restart
fi
